# Prepare ~~Chicago Crime Data~~ UFO Sightings Kaggle Data

- Original Notebook Source: https://github.com/coding-dojo-data-science/preparing-chicago-crime-data
- Updated 02/09/23

>- This notebook will process a "Crimes - 2001 to Preset.csv" crime file in your Downloads folder and save it as smaller .csv's in a new "Data/Chicago/" folder inside this notebook's folder/repo.

# INSTRUCTIONS

- 1) Go to the Chicago Data Portal's page for ["Crimes - 2001 to Preset"](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2).

- 2) Click on the Export button on the top right and select CSV. 
    - Save the file to your Downloads folder instead of your repository. **The file is too big for a repository.**
    
    
    
- 3) Wait for the full file to download. 
    - It is very large (over >1.7GB and may take several minutes to fully download.)
    
    
- 4) Once the download is complete, change `RAW_FILE` variable below to match the filepath to the downloaded file.

## ðŸš¨ Set the correct `RAW_FILE` path

- The cell below will attempt to check your Downloads folder for any file with a name that contains "Crimes_-_2001_to_Present".
    - If you know the file path already, you can skip the next cell and just manually set the RAW_FILE variable in the following code cell.

In [1]:
## Run the cell below to attempt to programmatically find your crime file
import os,glob

## Getting the home folder from environment variables
home_folder = os.environ['HOME']
# print("- Your Home Folder is: " + home_folder)

## Check for downloads folder
if 'Downloads' in os.listdir(home_folder):
    
    
    # Print the Downloads folder path
    dl_folder = os.path.abspath(os.path.join(home_folder,'Downloads'))
    print(f"- Your Downloads folder is '{dl_folder}/'\n")
    
    ## checking for crime files using glob
    crime_files = sorted(glob.glob(dl_folder+'/**/Crimes_-_2001_to_Present*',recursive=True))
    
    # If more than 
    if len(crime_files)==1:
        RAW_FILE = crime_files[0]
        
    elif len(crime_files)>1:
        print('[i] The following files were found:')
        
        for i, fname in enumerate(crime_files):
            print(f"\tcrime_files[{i}] = '{fname}'")
        print(f'\n- Please fill in the RAW_FILE variable in the code cell below with the correct filepath.')

else:
    print(f'[!] Could not programmatically find your downloads folder.')
    print('- Try using Finder (on Mac) or File Explorer (Windows) to navigate to your Downloads folder.')

- Your Downloads folder is '/Users/codingdojo/Downloads/'

In [2]:
## (Required) MAKE SURE TO CHANGE THIS VARIABLE TO MATCH YOUR LOCAL FILE NAME
RAW_FILE = "/Users/codingdojo/Downloads/scrubbed.csv" #(or slice correct index from the crime_files list)

if RAW_FILE == "YOUR FILEPATH HERE":
	raise Exception("You must update the RAW_FILE variable to match your local filepath.")
	
RAW_FILE

'/Users/codingdojo/Downloads/scrubbed.csv'

In [3]:
## (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = '../Data/ufos/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# ðŸ”„ Full Workflow

- Now that your RAW_FILE variable is set either:
    - On the toolbar, click on the Kernel menu > "Restart and Run All".
    - OR click on this cell first, then on the toolbar click on the "Cell" menu > "Run All Below"

In [4]:
import pandas as pd
pd.set_option('display.max_columns', 100)
pd.set_option('display.float_format',lambda x: f"{x:,.2f}")

In [5]:
chicago_full = pd.read_csv(RAW_FILE)
chicago_full

/var/folders/rf/vw4r41jd7vd95x1w0dth7v9h0000gp/T/ipykernel_3253/346346930.py:1: DtypeWarning: Columns (5,9) have mixed types. Specify dtype option on import or set low_memory=False.
  chicago_full = pd.read_csv(RAW_FILE)

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.94
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.58
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.92
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.65
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.80
...,...,...,...,...,...,...,...,...,...,...,...
80327,9/9/2013 21:15,nashville,tn,us,light,600.00,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.17,-86.78
80328,9/9/2013 22:00,boise,id,us,circle,"1,200.00",20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.61,-116.20
80329,9/9/2013 22:00,napa,ca,us,other,"1,200.00",hour,Napa UFO&#44,9/30/2013,38.30,-122.28
80330,9/9/2013 22:20,vienna,va,us,circle,5.00,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.90,-77.27
80331,9/9/2013 23:00,edmond,ok,us,cigar,"1,020.00",17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.65,-97.48

In [6]:
### FROM CLASS
## replace 24:00 with 23:59
chicago_full['datetime'] = chicago_full["datetime"].str.replace(" 24:00"," 23:59")
chicago_full = chicago_full.rename({'datetime':"Date"},axis=1)

In [7]:
# explicitly setting the format to speed up pd.to_datetime
# date_format = "%m/%d/%Y %H:%M:%S %p"
# date_format = "%m/%d/%Y %H:%M"

In [8]:
# ### Demonstrating/testing date_format
# example = chicago_full.loc[0,'Date']
# display(example)
# pd.to_datetime(example,format=date_format)

In [9]:
# this cell can take up to 1 min to run
chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'])#, format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full = chicago_full.set_index('Datetime')
chicago_full

,Date,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
Datetime,,,,,,,,,,,
1906-11-11 00:00:00,11/11/1906 00:00,wien (austria),NaN,NaN,other,10800,3 h,The oldest professional photo of a UFO object ...,12/23/2002,48.208174,16.37
1910-01-01 23:59:00,1/1/1910 23:59,kirksville (near),mo,us,disk,120,minutes,Historical sighting (1903 - 1913) Northern Mis...,9/15/2005,40.1947222,-92.58
1910-06-01 15:00:00,6/1/1910 15:00,wills point,tx,us,cigar,120,2 minutes,Cigar shaped object moving from West to East,4/16/2005,32.7091667,-96.01
1916-04-05 13:00:00,4/5/1916 13:00,france (above; from aircraft),NaN,NaN,cigar,60,about 1 min.,((NUFORC Note: Possible hoax. PD)) Saw 3 ci...,3/9/2004,46.227638,2.21
1920-06-11 21:00:00,6/11/1920 21:00,cicero,in,us,unknown,60,1 minute,((NUFORC Note: Probable hoax. Note date. PD...,5/12/2009,40.1238889,-86.01
...,...,...,...,...,...,...,...,...,...,...,...
2014-05-07 21:10:00,5/7/2014 21:10,naugatuck,ct,us,unknown,300,5 minutes,Large formation of lights in western sky&#44 f...,5/8/2014,41.4858333,-73.05
2014-05-07 21:20:00,5/7/2014 21:20,hillsboro,mo,us,fireball,360,4-6 minutes,Round slow moving silent ball looked like a ca...,5/8/2014,38.2322222,-90.56
2014-05-07 23:30:00,5/7/2014 23:30,san isidro,nm,NaN,unknown,15,15 seconds,2 red lights gliding across sky&#44 then green...,5/8/2014,35.563363,-106.77
2014-05-08 00:00:00,5/8/2014 00:00,memphis,tn,us,rectangle,900,15 minutes,Standing at my window around 0:00 brilliantly ...,5/8/2014,35.1494444,-90.05
2014-05-08 18:45:00,5/8/2014 18:45,inverloch (australia),NaN,au,light,300,5 minutes,Bright orange light travelling above inverloch...,5/8/2014,-38.626591,145.72

In [10]:
(chicago_full.isna().sum()/len(chicago_full)).round(2)

Date                   0.00
city                   0.00
state                  0.07
country                0.12
shape                  0.02
duration (seconds)     0.00
duration (hours/min)   0.00
comments               0.00
date posted            0.00
latitude               0.00
longitude              0.00
dtype: float64

## Separate the Full Dataset by Years

In [11]:
# save the years for every crime
chicago_full["Year"] = chicago_full.index.year
chicago_full["Year"] = chicago_full["Year"].astype(str)
chicago_full["Year"].value_counts()

2012    7357
2013    7037
2011    5107
2008    4820
2009    4541
        ...
1929       1
1925       1
1920       1
1916       1
1906       1
Name: Year, Length: 87, dtype: int64

In [12]:
## Dropping unneeded columns to reduce file size
drop_cols = []#"X Coordinate","Y Coordinate", "Community Area","FBI Code",
#              "Case Number","Updated On",'Block','Location','IUCR']

In [13]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols).sort_index()#.reset_index()
chicago_final

,Date,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude,Year
Datetime,,,,,,,,,,,,
1906-11-11 00:00:00,11/11/1906 00:00,wien (austria),NaN,NaN,other,10800,3 h,The oldest professional photo of a UFO object ...,12/23/2002,48.208174,16.37,1906
1910-01-01 23:59:00,1/1/1910 23:59,kirksville (near),mo,us,disk,120,minutes,Historical sighting (1903 - 1913) Northern Mis...,9/15/2005,40.1947222,-92.58,1910
1910-06-01 15:00:00,6/1/1910 15:00,wills point,tx,us,cigar,120,2 minutes,Cigar shaped object moving from West to East,4/16/2005,32.7091667,-96.01,1910
1916-04-05 13:00:00,4/5/1916 13:00,france (above; from aircraft),NaN,NaN,cigar,60,about 1 min.,((NUFORC Note: Possible hoax. PD)) Saw 3 ci...,3/9/2004,46.227638,2.21,1916
1920-06-11 21:00:00,6/11/1920 21:00,cicero,in,us,unknown,60,1 minute,((NUFORC Note: Probable hoax. Note date. PD...,5/12/2009,40.1238889,-86.01,1920
...,...,...,...,...,...,...,...,...,...,...,...,...
2014-05-07 21:10:00,5/7/2014 21:10,naugatuck,ct,us,unknown,300,5 minutes,Large formation of lights in western sky&#44 f...,5/8/2014,41.4858333,-73.05,2014
2014-05-07 21:20:00,5/7/2014 21:20,hillsboro,mo,us,fireball,360,4-6 minutes,Round slow moving silent ball looked like a ca...,5/8/2014,38.2322222,-90.56,2014
2014-05-07 23:30:00,5/7/2014 23:30,san isidro,nm,NaN,unknown,15,15 seconds,2 red lights gliding across sky&#44 then green...,5/8/2014,35.563363,-106.77,2014
2014-05-08 00:00:00,5/8/2014 00:00,memphis,tn,us,rectangle,900,15 minutes,Standing at my window around 0:00 brilliantly ...,5/8/2014,35.1494444,-90.05,2014
2014-05-08 18:45:00,5/8/2014 18:45,inverloch (australia),NaN,au,light,300,5 minutes,Bright orange light travelling above inverloch...,5/8/2014,-38.626591,145.72,2014

In [14]:
chicago_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 80332 entries, 1906-11-11 00:00:00 to 2014-05-08 18:45:00
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  80332 non-null  object
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80332 non-null  object
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  object
 9   latitude              80332 non-null  object
 10  longitude             80332 non-null  float64
 11  Year                  80332 non-null  object
dtypes: float64(1), object(11)
memory usage: 8.0+ MB

In [15]:
chicago_final.memory_usage(deep=True).astype(float)

Index                     642,656.00
Date                    5,778,762.00
city                    5,490,068.00
state                   4,583,069.00
country                 4,478,498.00
shape                   5,009,498.00
duration (seconds)      4,385,582.00
duration (hours/min)    5,322,692.00
comments               11,240,765.00
date posted             5,302,130.00
latitude                4,844,815.00
longitude                 642,656.00
Year                    4,900,252.00
dtype: float64

In [16]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['1906', '1910', '1916', '1920', '1925', '1929', '1930', '1931',
       '1933', '1934', '1936', '1937', '1939', '1941', '1942', '1943',
       '1944', '1945', '1946', '1947', '1948', '1949', '1950', '1951',
       '1952', '1953', '1954', '1955', '1956', '1957', '1958', '1959',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967',
       '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975',
       '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014'],
      dtype=object)

In [17]:
FINAL_DROP = ['Datetime','Year']#,'Location Description']

In [18]:
## set save location 

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"[i] Saving .csv's to {OUTPUT_FOLDER}")
## loop through years
for year in year_bins:
    
    ## save temp slices of dfs to save.
    temp_df = chicago_final.loc[ year]
    temp_df = temp_df.reset_index(drop=False)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # save as csv to output folder
    fname_temp = f"{OUTPUT_FOLDER}UFO-Sightings_{year}.csv"#.gz
    temp_df.to_csv(fname_temp,index=False)

    print(f"- Succesfully saved {fname_temp}")

[i] Saving .csv's to ../Data/ufos/
- Succesfully saved ../Data/ufos/UFO-Sightings_1906.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1910.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1916.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1920.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1925.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1929.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1930.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1931.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1933.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1934.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1936.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1937.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1939.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1941.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1942.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1943.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1944.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1945.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1946.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1947.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1948.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1949.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1950.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1951.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1952.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1953.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1954.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1955.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1956.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1957.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1958.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1959.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1960.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1961.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1962.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1963.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1964.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1965.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1966.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1967.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1968.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1969.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1970.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1971.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1972.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1973.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1974.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1975.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1976.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1977.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1978.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1979.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1980.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1981.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1982.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1983.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1984.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1985.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1986.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1987.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1988.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1989.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1990.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1991.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1992.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1993.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1994.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1995.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1996.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1997.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1998.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_1999.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2000.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2001.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2002.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2003.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2004.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2005.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2006.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2007.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2008.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2009.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2010.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2011.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2012.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2013.csv
- Succesfully saved ../Data/ufos/UFO-Sightings_2014.csv

In [19]:
saved_files = sorted(glob.glob(OUTPUT_FOLDER+'*.*csv'))
saved_files

['../Data/ufos/UFO-Sightings_1906.csv',
 '../Data/ufos/UFO-Sightings_1910.csv',
 '../Data/ufos/UFO-Sightings_1916.csv',
 '../Data/ufos/UFO-Sightings_1920.csv',
 '../Data/ufos/UFO-Sightings_1925.csv',
 '../Data/ufos/UFO-Sightings_1929.csv',
 '../Data/ufos/UFO-Sightings_1930.csv',
 '../Data/ufos/UFO-Sightings_1931.csv',
 '../Data/ufos/UFO-Sightings_1933.csv',
 '../Data/ufos/UFO-Sightings_1934.csv',
 '../Data/ufos/UFO-Sightings_1936.csv',
 '../Data/ufos/UFO-Sightings_1937.csv',
 '../Data/ufos/UFO-Sightings_1939.csv',
 '../Data/ufos/UFO-Sightings_1941.csv',
 '../Data/ufos/UFO-Sightings_1942.csv',
 '../Data/ufos/UFO-Sightings_1943.csv',
 '../Data/ufos/UFO-Sightings_1944.csv',
 '../Data/ufos/UFO-Sightings_1945.csv',
 '../Data/ufos/UFO-Sightings_1946.csv',
 '../Data/ufos/UFO-Sightings_1947.csv',
 '../Data/ufos/UFO-Sightings_1948.csv',
 '../Data/ufos/UFO-Sightings_1949.csv',
 '../Data/ufos/UFO-Sightings_1950.csv',
 '../Data/ufos/UFO-Sightings_1951.csv',
 '../Data/ufos/UFO-Sightings_1952.csv',
 '../Data/ufos/UFO-Sightings_1953.csv',
 '../Data/ufos/UFO-Sightings_1954.csv',
 '../Data/ufos/UFO-Sightings_1955.csv',
 '../Data/ufos/UFO-Sightings_1956.csv',
 '../Data/ufos/UFO-Sightings_1957.csv',
 '../Data/ufos/UFO-Sightings_1958.csv',
 '../Data/ufos/UFO-Sightings_1959.csv',
 '../Data/ufos/UFO-Sightings_1960.csv',
 '../Data/ufos/UFO-Sightings_1961.csv',
 '../Data/ufos/UFO-Sightings_1962.csv',
 '../Data/ufos/UFO-Sightings_1963.csv',
 '../Data/ufos/UFO-Sightings_1964.csv',
 '../Data/ufos/UFO-Sightings_1965.csv',
 '../Data/ufos/UFO-Sightings_1966.csv',
 '../Data/ufos/UFO-Sightings_1967.csv',
 '../Data/ufos/UFO-Sightings_1968.csv',
 '../Data/ufos/UFO-Sightings_1969.csv',
 '../Data/ufos/UFO-Sightings_1970.csv',
 '../Data/ufos/UFO-Sightings_1971.csv',
 '../Data/ufos/UFO-Sightings_1972.csv',
 '../Data/ufos/UFO-Sightings_1973.csv',
 '../Data/ufos/UFO-Sightings_1974.csv',
 '../Data/ufos/UFO-Sightings_1975.csv',
 '../Data/ufos/UFO-Sightings_1976.csv',
 '../Data/ufos/UFO-Sightings_1977.csv',
 '../Data/ufos/UFO-Sightings_1978.csv',
 '../Data/ufos/UFO-Sightings_1979.csv',
 '../Data/ufos/UFO-Sightings_1980.csv',
 '../Data/ufos/UFO-Sightings_1981.csv',
 '../Data/ufos/UFO-Sightings_1982.csv',
 '../Data/ufos/UFO-Sightings_1983.csv',
 '../Data/ufos/UFO-Sightings_1984.csv',
 '../Data/ufos/UFO-Sightings_1985.csv',
 '../Data/ufos/UFO-Sightings_1986.csv',
 '../Data/ufos/UFO-Sightings_1987.csv',
 '../Data/ufos/UFO-Sightings_1988.csv',
 '../Data/ufos/UFO-Sightings_1989.csv',
 '../Data/ufos/UFO-Sightings_1990.csv',
 '../Data/ufos/UFO-Sightings_1991.csv',
 '../Data/ufos/UFO-Sightings_1992.csv',
 '../Data/ufos/UFO-Sightings_1993.csv',
 '../Data/ufos/UFO-Sightings_1994.csv',
 '../Data/ufos/UFO-Sightings_1995.csv',
 '../Data/ufos/UFO-Sightings_1996.csv',
 '../Data/ufos/UFO-Sightings_1997.csv',
 '../Data/ufos/UFO-Sightings_1998.csv',
 '../Data/ufos/UFO-Sightings_1999.csv',
 '../Data/ufos/UFO-Sightings_2000.csv',
 '../Data/ufos/UFO-Sightings_2001.csv',
 '../Data/ufos/UFO-Sightings_2002.csv',
 '../Data/ufos/UFO-Sightings_2003.csv',
 '../Data/ufos/UFO-Sightings_2004.csv',
 '../Data/ufos/UFO-Sightings_2005.csv',
 '../Data/ufos/UFO-Sightings_2006.csv',
 '../Data/ufos/UFO-Sightings_2007.csv',
 '../Data/ufos/UFO-Sightings_2008.csv',
 '../Data/ufos/UFO-Sightings_2009.csv',
 '../Data/ufos/UFO-Sightings_2010.csv',
 '../Data/ufos/UFO-Sightings_2011.csv',
 '../Data/ufos/UFO-Sightings_2012.csv',
 '../Data/ufos/UFO-Sightings_2013.csv',
 '../Data/ufos/UFO-Sightings_2014.csv']

In [20]:
## create a README.txt for the zip files
readme = """Source URL: 
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])
"""
print(readme)


with open(f"{OUTPUT_FOLDER}README.txt",'w') as f:
    f.write(readme)

Source URL:
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])

## Confirmation

- Follow the example usage above to test if your files were created successfully.

In [21]:
# get list of files from folder
crime_files = sorted(glob.glob(OUTPUT_FOLDER+"*.csv"))
df = pd.concat([pd.read_csv(f) for f in crime_files])
df

,Date,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,11/11/1906 00:00,wien (austria),NaN,NaN,other,10800,3 h,The oldest professional photo of a UFO object ...,12/23/2002,48.21,16.37
0,1/1/1910 23:59,kirksville (near),mo,us,disk,120,minutes,Historical sighting (1903 - 1913) Northern Mis...,9/15/2005,40.19,-92.58
1,6/1/1910 15:00,wills point,tx,us,cigar,120,2 minutes,Cigar shaped object moving from West to East,4/16/2005,32.71,-96.01
0,4/5/1916 13:00,france (above; from aircraft),NaN,NaN,cigar,60,about 1 min.,((NUFORC Note: Possible hoax. PD)) Saw 3 ci...,3/9/2004,46.23,2.21
0,6/11/1920 21:00,cicero,in,us,unknown,60,1 minute,((NUFORC Note: Probable hoax. Note date. PD...,5/12/2009,40.12,-86.01
...,...,...,...,...,...,...,...,...,...,...,...
2255,5/7/2014 21:10,naugatuck,ct,us,unknown,300.00,5 minutes,Large formation of lights in western sky&#44 f...,5/8/2014,41.49,-73.05
2256,5/7/2014 21:20,hillsboro,mo,us,fireball,360.00,4-6 minutes,Round slow moving silent ball looked like a ca...,5/8/2014,38.23,-90.56
2257,5/7/2014 23:30,san isidro,nm,NaN,unknown,15.00,15 seconds,2 red lights gliding across sky&#44 then green...,5/8/2014,35.56,-106.77
2258,5/8/2014 00:00,memphis,tn,us,rectangle,900.00,15 minutes,Standing at my window around 0:00 brilliantly ...,5/8/2014,35.15,-90.05
2259,5/8/2014 18:45,inverloch (australia),NaN,au,light,300.00,5 minutes,Bright orange light travelling above inverloch...,5/8/2014,-38.63,145.72

In [22]:
years = df['Date'].map(lambda x: x.split()[0].split('/')[-1])
years.value_counts().sort_index()

1906       1
1910       2
1916       1
1920       1
1925       1
        ...
2010    4283
2011    5107
2012    7357
2013    7037
2014    2260
Name: Date, Length: 87, dtype: int64

## Summary

- The chicago crime dataset has now been saved to your repository as csv files. 
- You should save your notebook, commit your work and push to GitHub using GitHub desktop.